# Generated by Django 4.2.17 on 2024-12-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
