# Generated by Django 4.2.17 on 2024-12-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_publisher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publisher',
            table=None,
        ),
    ]
